---
- name: Install nginx
  yum:
    name: nginx
    state: present
  tags: install-nginx

- name: Enable and Start nginx systemd unit
  systemd: name=nginx enabled=yes state=started
  tags: install-nginx

- name: Remove nginx
  yum:
    name: nginx
    state: removed
  tags: uninstall-nginx
